spring:
  application:
    name: inventory-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7000/test-container
    username: #USERNAME
    password: #PASSWORD
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
server:
  port: 8080
